#!/usr/bin/env bash
# This Bash script will display information about the subdomains

domain_check () {
    parse_script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $parse_script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_check "$1" "www"
  domain_check "$1" "lb-01"
  domain_check "$1" "web-01"
  domain_check "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_check "$1" "$2"
fi
