#!/usr/bin/env bash
#this script displays good or bad luck and Best school in
#a while loop 10 time iteration
i=0

while ((i < 10)); do
	if ((i == 7)); then
		echo "good luck"
	
		elif ((i == 3)); then
			echo "bad luck"
		else 
			echo "Best School"
	fi
	((i+=1))
done
