#!/usr/bin/env bash
#this script displays good or bad luck and Best school in
#a while loop 10 time iteration
i=0

while ((i < 20)); do
	echo "$i"
	case $i in
		4)
			echo "bad luck from china";;
		9)
			echo "bad luck from japan";;
		17)
			echo " bad luck from italy";;
	esac
	((i+=1))
done
